services:
  - type: web
    name: skillwallet-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATA_DIR
        value: /var/data
